name: Update Data

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Daily at 00:00 UTC

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to push changes
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Generate data.json
        run: node update-data.js
      
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data.json
          git commit -m "Auto-update data.json" || echo "No changes"
          git push
