name: Update Data
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 21 * * *' # Каждый день в 12:00 МСК

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: node update-data.js
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data.json
          git commit -m "Auto-update data.json" || echo "No changes"
          git push
